---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://docs.ansible.com/playbooks_intro.html for more information about handlers.

- name: restart_chrony_centos
  service:
    name: chronyd
    state: restarted

- name: restart_chrony_ubuntu
  service: 
    name: chrony
    state: restarted
