---
#This playbook will install mariadb and create db user and give permissions.

- name: Install Mariadb package
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ mariadb_packages }}"

- name: Configure SELinux to start mysql on any port
  seboolean:
    name: mysql_connect_any
    state: true
    persistent: yes
   
- name: Create Mysql configuration file
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  notify: restart mariadb

- name: Start Mysql Service
  service:
    name: mariadb
    state: started
    enabled: yes

- name: insert iptables rule
  lineinfile:
    dest: /etc/sysconfig/iptables-config
    state: present
    regexp: "{{ mysql_port }}"
    insertafter: "^:OUTPUT "
    line: "-A INPUT -p tcp  --dport {{ mysql_port }} -j  ACCEPT"
  notify: restart iptables
    
- name: Create Application Database
  mysql_db:
    name: "{{ dbname }}"
    state: present

- name: Create Application DB User
  mysql_user:
    name: "{{ dbuser }}"
    password: "{{ upassword }}"
    priv: "*.*:ALL"
    host: '%'
    state: present
