---
# These tasks are responsible for copying the latest dev/production code from
# the version control system.

- name: Creates the index.php file Ubuntu
  template:
    src: inde.php.j2
    dest: /var/www/html/index.php
    owner: root
    group: root
  notify: restart apache   
  when: ansible_distribution == "Ubuntu"

- name: Creates the index.php file Centos
  template:
    src: inde.php.j2
    dest: /var/www/html/index.php
    owner: root
    group: root
  notify: restart httpd
  when: ansible_distribution == "CentOS"
