---
# This playbook contains common plays that will be run on all nodes.
#instalamos python3-apt en ubutntu
#Cambiamos yum por apt
#Cambiamos ntp por chrony

- name: Install chrony Ubuntu
  apt:
    name: chrony
    state: present
  when: ansible_distribution == 'Ubuntu'
   

- name: install chrony centos
  yum:
    name: chrony
    state: present
  when: ansible_distribution == 'CentOS' 

- name: Configure chrony file CentOs
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
  when: ansible_distribution == "CentOS"
  notify: restart_chrony_centos
 
- name: Configure chrony file Ubuntu
  template:
    src: ntp.conf.j2
    dest: /etc/chrony/chrony.conf
  when: ansible_distribution == "Ubuntu"  
  notify: restart_chrony_ubuntu


- name: Start the chrony service Ubuntu
  service:
    name: chrony
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"


- name: Start the chrony service Centos
  service:
    name: chronyd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"

 
- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false
